api/urls.py
from rest_framework.routers import SimpleRouter
from .views import UserViewSet, HistoryList, ResourcesList, NewsList

router = SimpleRouter()

router.register('users', UserViewSet, 'users')
router.register('history', HistoryList, 'history')
router.register('resources', ResourcesList, 'resources')
router.register('news', NewsList, 'news')

urlpatterns = router.urls

bayel_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from balance.views import SearchHistoryView
from bayel_project import settings
from pages.views import ReportSearchView, SendFormTelegram
from users.views import SearchResultsView, OperatorDetails

handler404 = 'pages.views.my_404'
handler403 = 'pages.views.my_403'
handler400 = 'pages.views.my_400'
handler503 = 'pages.views.my_503'

urlpatterns = [
    path('bashkaru/nurlan', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('rest_auth.urls')),
]

urlpatterns += i18n_patterns(
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('balance/', include('balance.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('search_history/', SearchHistoryView.as_view(), name='search_history'),
    path('report_search/', ReportSearchView.as_view(), name='report_search'),
    path('send-form-tg/', SendFormTelegram.as_view(), name='send_message'),

    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.
class Statistics(models.Model):
    registration_users = models.IntegerField(verbose_name=_('Катталган адамдар'))
    presents = models.IntegerField(verbose_name=_('Алынган белектер'))
    starts = models.IntegerField(verbose_name=_('Ийгилик ээлери'))


class Resources(models.Model):
    title = models.CharField(verbose_name='Название файла', max_length=255)
    file = models.FileField(verbose_name='Файл')

    def __str__(self):
        return f'{self.title}'

news/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import News


class CreateNewsForm(forms.ModelForm):
    title = forms.CharField(label="Аталышы", error_messages={'required': _(u"Бул тилке бош")}, required=True,
                            widget=forms.TextInput(
                                attrs={'class': 'form-control', 'placeholder': 'Аталышы'}))
    title_ru = forms.CharField(label="Заголовок на русском", error_messages={'required': _(u"Бул тилке бош")},
                               required=True,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control'}))
    description = forms.CharField(label="Баяны", error_messages={'required': _(u"Бул тилке бош")}, required=True,
                                  widget=forms.Textarea(
                                      attrs={'class': 'form-control', 'placeholder': 'Баяны'}))
    description_ru = forms.CharField(label="Описание на русском", error_messages={'required': _(u"Бул тилке бош")},
                                     required=True,
                                     widget=forms.Textarea(
                                         attrs={'class': 'form-control', 'placeholder': 'Описание на русском'}))

    class Meta:
        model = News
        fields = ['title', 'title_ru', 'description', 'description_ru', 'image']


# class UpdateNewsForm(forms.ModelForm):
    # title = forms.CharField(label="Аталышы", error_messages={'required': _(u"Бул тилке бош")}, required=True,
    #                         widget=forms.TextInput(
    #                             attrs={'class': 'form-control', 'placeholder': 'Аталышы'}))
    # title_ru = forms.CharField(label="Заголовок на русском", error_messages={'required': _(u"Бул тилке бош")},
    #                            required=True,
    #                            widget=forms.TextInput(
    #                                attrs={'class': 'form-control'}))
    # description = forms.CharField(label="Баяны", error_messages={'required': _(u"Бул тилке бош")}, required=True,
    #                               widget=forms.Textarea(
    #                                   attrs={'class': 'form-control', 'placeholder': 'Баяны'}))
    # description_ru = forms.CharField(label="Описание на русском", error_messages={'required': _(u"Бул тилке бош")},
    #                                  required=True,
    #                                  widget=forms.Textarea(
    #                                      attrs={'class': 'form-control', 'placeholder': 'Описание на русском'}))
    #
    # class Meta:
    #     model = News
    #     fields = ['title', 'title_ru', 'description', 'description_ru', 'image']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Office
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label="Логин", error_messages={'required': _(u"Бул тилке бош")}, required=True,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Логин'}))
    user_fullname = forms.CharField(label=_(u'Аты Жөнү'), error_messages={'required': _(u"Бул тилке бош")},
                                    required=True,
                                    widget=forms.TextInput(
                                        attrs={'class': 'form-control', 'placeholder': _(u'Аты Жөнү')}))
    user_phone = forms.CharField(label="Телефон", error_messages={'required': _(u"Бул тилке бош")}, required=True,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': _(u'Телефон номери')}))
    user_by_whom = forms.ModelChoiceField(label=_(u'Жетекчи'), required=False,
                                          queryset=CustomUser.objects.filter(is_staff=False,
                                                                             follower2=None),
                                          empty_label=_(u"Кимден"),
                                          widget=forms.Select(attrs={'class': 'form-control ', 'data-plugin': 'select2',
                                                                     'data-minimum-input-length': '1'}))
    user_office = forms.ModelChoiceField(label=_(u'Регион'), required=True,
                                         queryset=Office.objects.all(),
                                         empty_label=_(u"Регион"),
                                         widget=forms.Select(attrs={'class': 'form-control my-form'}))
    password1 = forms.CharField(label=_(u'Сыр сөз'), error_messages={'required': _(u"Бул тилке бош")}, required=True,
                                min_length=8, validators=[
            RegexValidator('^(\w+\d+|\d+\w+)+$',
                           message=_(u'Сырсөз англис тамга жана сандардан жыйындысы болуп саналат'))],
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control',
                                           'placeholder': _(u'Сыр сөз'), 'value': 'bayel123'}), )
    password2 = forms.CharField(label=_(u'Сыр сөздү кайталаңыз'), error_messages={'required': _(u"Бул тилке бош")},
                                required=True,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': _(u'Сыр сөздү кайталаңыз'),
                                           'value': 'bayel123'}))
    terms = forms.BooleanField(label=_(u'Мен "Бай Эл" программасынын  Купуялык саясатын окуп чыгып, кабыл алып жатам'),
                               error_messages={'required': _(u"Бул тилке бош")}, required=True,
                               widget=forms.CheckboxInput(
                                   attrs={'class': 'form-control terms',
                                          'onclick': "showMe('autoUpdate', 'picture-signup')",
                                          'checked': 'true'}), )

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            'username', 'user_fullname', 'user_phone', 'user_by_whom', 'user_office',)

    def clean_username(self):
        username = self.cleaned_data['username']
        r = CustomUser.objects.filter(username=username)
        if r.count():
            raise ValidationError("Логин уже используется, пожалуйста введите другой логин")
        return username

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Пароли не совпадают")
        return password2


class CustomUserChangeForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        self.fields['user_by_whom'].queryset = CustomUser.objects.filter(is_staff=False)
        password = forms.CharField(label=False)

    username = forms.CharField(label="Логин", error_messages={'required': _(u"Бул тилке бош")}, required=True,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Логин'}))
    user_fullname = forms.CharField(label=_(u'Аты Жөнү'), error_messages={'required': _(u"Бул тилке бош")},
                                    required=True,
                                    widget=forms.TextInput(
                                        attrs={'class': 'form-control', 'placeholder': _(u'Аты Жөнү')}))
    user_notes = forms.CharField(label=_(u'Белги'), required=False,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': _(u'Белги')}))
    user_office = forms.ModelChoiceField(label=_(u'Регион'), required=True,
                                         queryset=Office.objects.all(),
                                         empty_label=_(u"Регион"),
                                         widget=forms.Select(attrs={'class': 'form-control my-form'}))
    user_by_whom = forms.ModelChoiceField(label=_(u'Жетекчи'), required=False,
                                          queryset=CustomUser.objects.filter(is_staff=False,
                                                                             follower2=None),
                                          empty_label=_(u"Кимден"),
                                          widget=forms.Select(attrs={'class': 'form-control ', 'data-plugin': 'select2',
                                                                     'data-minimum-input-length': '1'}))
    user_phone = forms.CharField(label="Телефон", error_messages={'required': _(u"Бул тилке бош")}, required=True,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': _(u'Телефон')}))
    user_balance = forms.CharField(label="Доступно для снятия", error_messages={'required': _(u"Бул тилке бош")},
                                   required=True,
                                   widget=forms.TextInput(
                                       attrs={'class': 'form-control', 'placeholder': _(u'Доступно для снятия')}))
    user_total_balance = forms.CharField(label="Всего заработанно", error_messages={'required': _(u"Бул тилке бош")},
                                         required=True,
                                         widget=forms.TextInput(
                                             attrs={'class': 'form-control', 'placeholder': _(u'Всего заработанно')}))
    user_balance13 = forms.CharField(label="Доступно для снятия 13", error_messages={'required': _(u"Бул тилке бош")},
                                     required=True,
                                     widget=forms.TextInput(
                                         attrs={'class': 'form-control', 'placeholder': _(u'Доступно для снятия 13')}))
    user_total_balance13 = forms.CharField(label="Всего заработанно 13",
                                           error_messages={'required': _(u"Бул тилке бош")},
                                           required=True,
                                           widget=forms.TextInput(
                                               attrs={'class': 'form-control',
                                                      'placeholder': _(u'Всего заработанно 13')}))
    user_balance13_hidden = forms.CharField(label="Скрыто 13",
                                            error_messages={'required': _(u"Бул тилке бош")},
                                            required=True,
                                            widget=forms.TextInput(
                                                attrs={'class': 'form-control',
                                                       'placeholder': _(u'Скрыто 13')}))
    followers = forms.CharField(label="Подписчики", error_messages={'required': _(u"Бул тилке бош")},
                                required=True,
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control', 'placeholder': _(u'Подписчики')}))
    followers13 = forms.CharField(label="Подписчики 13", error_messages={'required': _(u"Бул тилке бош")},
                                  required=True,
                                  widget=forms.TextInput(
                                      attrs={'class': 'form-control', 'placeholder': _(u'Подписчики 13')}))
    followers13_passive = forms.CharField(label="Подписчики скрытые 13",
                                          error_messages={'required': _(u"Бул тилке бош")},
                                          required=True,
                                          widget=forms.TextInput(
                                              attrs={'class': 'form-control',
                                                     'placeholder': _(u'Подписчики скрытые 13')}))

    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            'username', 'user_fullname', 'user_image', 'user_by_whom', 'user_phone', 'user_balance13',
            'user_total_balance13', 'status_user_own', 'product13', 'followers13',

templates/pages/profile.html
{% extends 'manager_base.html' %}
{% load static %}
{% block content %}

{% endblock %}

templates/pages/report.html
{% extends 'manager_base.html' %}
{% load static i18n l10n %}
{% block content %}
    <!-- Page -->
    <div class="page">
        <div class="page-header">
            <h1 class="page-title">{% trans "Колдонуучулардын тизмеси" %}</h1>
        </div>
        <div class="page-content container-fluid">
            <div class="row">
                <div class="col-xl-12">
                    <!-- Panel Filtering rows -->
                    <div class="panel">
                        <header class="panel-heading" style="display: flex">
                            <h3 class="panel-title">Введите дату</h3>
                        </header>
                        <div class="panel-body">
                            <form action="{% url 'report_search' %}" method="get">
                                <input name="q" type="date" class="form-control search-input-list1"
                                       style="width: 300px; float: left;" required>
                                <input name="end-date" type="date" class="form-control search-input-list1"
                                       style="width: 300px; float: left;">
                                <select name="user_office" class="form-control my-form inline-block width-20 ml-2"
                                        id="id_user_office">
                                    {% if user_office_context %}
                                        <option value="{{ user_office_context.office_name }}"
                                                selected="">{{ user_office_context.office_name }}</option>
                                    {% else %}
                                        <option value="" selected="">Регион</option>
                                    {% endif %}
                                    {% for office in all_offices %}
                                        <option value="{{ office.office_name }}">{{ office.office_name }}</option>
                                    {% endfor %}
                                </select>
                                <button type="submit" class="btn btn-primary width-10" style="margin-left: 10px;">Поиск</button>
                            </form>
                            <table class="table table-bordered table-hover toggle-circle">
                                <thead>
                                <tr>
                                    <th data-name="id" data-type="number" data-breakpoints="xs">№</th>
                                    <th data-name="firstName">{% trans "Логин" %}</th>
                                    <th data-name="something">{% trans "ФИО" %}</th>
                                    <th data-name="something">Белги</th>
                                    <th data-name="firstName" class="balls-cell">{% trans "Баллы" %}</th>
                                    <th data-name="jobTitle" data-breakpoints="xs sm">{% trans "Телефон" %}</th>
                                    <th data-name="firstName" class="product-cell">Продукция</th>
                                    <th data-name="firstName" class="by-whom-cell">{% trans "Спонсордун ФИО" %}</th>
                                    {% if user.is_superuser %}
                                        <th data-name="lastName" class="management-cell">{% trans "Башкаруу" %}</th>
                                    {% elif user.is_cashier or user.is_staff %}
                                        <th data-name="lastName" class="management-cell">{% trans "Башкаруу" %}</th>
                                    {% endif %}
                                </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                            {% include 'paginator.html' with page=page_obj %}

                        </div>
                    </div>
                    <!-- End Panel Filtering -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Page -->
{% endblock %}

templates/pages/resource.html
{% extends 'manager_base.html' %}
{% load i18n static %}
{% block content %}
    <div class="container">
        <!-- Features start -->
        <section id="features" class="mt-lg-5">
            <div class="container">
                <div class="row">
                    <div class="col-md-10">
                        <div class="main-title wow fadeIn" data-wow-delay="300ms">
                            <h2> {% trans 'Ресурстар' %} </h2>
                        </div>
                    </div>
                </div>
                <div class="container cc_cursor">
                    {% if user.is_superuser %}
                        <a href="{% url 'resource_create' %}" class="btn btn-outline-success mb-lg-4">Добавить файл</a>
                    {% endif %}
                    <div class="card-deck mb-3 text-center cc_cursor">
                        {% for x in object_list|slice:":4" %}
                            <div class="card col-md-3 shadow-sm">
                                <div class="card-header">
                                    <h4 class="my-0 font-weight-normal">{{ x.title }}</h4>
                                </div>
                                <div class="card-body">
                                    <img src="{% static 'img/pdf.svg' %}" alt="" width="150px">
                                    <a href="{{ x.file.url }}" target="_blank"
                                       class="btn btn-lg btn-block btn-outline-primary cc_pointer mt-lg-4">{% trans 'Жүктөп алуу' %}</a>
                                    {% if user.is_superuser %}
                                        <a href="{% url 'resource_delete' x.pk %}" target="_blank"
                                           class="btn btn-lg btn-block btn-outline-danger cc_pointer mt-lg-4">{% trans 'Өчүрүү' %}</a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="card-deck mb-3 text-center cc_cursor">
                        {% for x in object_list|slice:"5:9" %}
                            <div class="card col-md-3 shadow-sm">
                                <div class="card-header">
                                    <h4 class="my-0 font-weight-normal">{{ x.title }}</h4>
                                </div>
                                <div class="card-body">
                                    <img src="{% static 'img/pdf.svg' %}" alt="" width="150px">
                                    <a href="{{ x.file.url }}" target="_blank"
                                       class="btn btn-lg btn-block btn-outline-primary cc_pointer mt-lg-4">{% trans 'Жүктөп алуу' %}</a>
                                    {% if user.is_superuser %}
                                        <a href="{% url 'resource_delete' x.pk %}" target="_blank"
                                           class="btn btn-lg btn-block btn-outline-danger cc_pointer mt-lg-4">{% trans 'Өчүрүү' %}</a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="card-deck mb-3 text-center cc_cursor">
                        {% for x in object_list|slice:"9:13" %}
                            <div class="card col-md-3 shadow-sm">
                                <div class="card-header">
                                    <h4 class="my-0 font-weight-normal">{{ x.title }}</h4>
                                </div>
                                <div class="card-body">
                                    <img src="{% static 'img/pdf.svg' %}" alt="" width="150px">
                                    <a href="{{ x.file.url }}" target="_blank"
                                       class="btn btn-lg btn-block btn-outline-primary cc_pointer mt-lg-4">{% trans 'Жүктөп алуу' %}</a>
                                    {% if user.is_superuser %}
                                        <a href="{% url 'resource_delete' x.pk %}" target="_blank"
                                           class="btn btn-lg btn-block btn-outline-danger cc_pointer mt-lg-4">{% trans 'Өчүрүү' %}</a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </section>
    </div>
    <!-- Features ends -->
{% endblock %}

templates/pages/resource_create.html
{% extends 'manager_base.html' %}
{% load i18n %}
{% block content %}
    <!-- Features start -->
    <section id="features">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="main-title wow fadeIn" data-wow-delay="300ms">
                        <h2>{% trans 'Файл кошуу' %}</h2>
                    </div>
                </div>
            </div>
            <div class="row mb-70">
                <div class="col-md-6">
                    <form action="" class="user-update-form" method="post" novalidate="novalidate" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p><label for="id_title">Название файла:</label><br>
                            {{ form.title }}</p>
                        <br>
                        <p><label for="id_file">Файл:</label> <br>{{form.file}}</p>

                        <div class="btn-signup">
                            <button type="submit" class="btn btn-outline-success signup-btn">{% trans 'Кошуу' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Features ends -->
{% endblock %}

templates/pages/resource_delete.html
{% extends 'manager_base.html' %}
{% load i18n %}
{% block content %}
    <!-- Features start -->
    <section id="features">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="main-title wow fadeIn" data-wow-delay="300ms">
                        <h2>{% trans 'Файл очуруу' %}</h2>
                    </div>
                </div>
            </div>
            <div class="row mb-70">
                <div class="col-md-6">
                    <form action="" class="user-update-form" method="post" novalidate="novalidate">
                        {% csrf_token %}
                        <div class="btn-signup">
                            <button type="submit" class="btn btn-outline-success signup-btn">Удалить</button>
                            <a href="{% url 'resource' %}" class="btn btn-outline-danger signup-btn"> Нет</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Features ends -->
{% endblock %}

templates/pages/statistic_update.html
{% extends 'manager_base.html' %}
{% load i18n %}
{% block content %}
    <!-- Features start -->
    <section id="features">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="main-title wow fadeIn" data-wow-delay="300ms">
                        <h2> Изменить статистику </h2>
                    </div>
                </div>
            </div>
            <div class="row mb-70">
                <div class="col-md-6">
                    <form action="" class="user-update-form" method="post" novalidate="novalidate">
                        {% csrf_token %}
                        <label for="id_registration_users">Катталган адамдар:</label>
                        <input type="number" name="registration_users" value="{{ object.registration_users }}"
                               required="" id="id_registration_users" class="form-control">

                        <label for="id_presents">Алынган белектер:</label>
                        <input type="number" name="presents" value="{{ object.presents }}" required="" id="id_presents"
                               class="form-control">

                        <label for="id_starts">Ийгилик ээлери:</label>
                        <input type="number" name="starts" value="{{ object.starts }}" required="" id="id_starts"
                               class="form-control">

                        <div class="btn-signup">
                            <button type="submit" class="btn btn-outline-success signup-btn">Сактоо</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Features ends -->
{% endblock %}

templates/pages/test.html
{% extends 'manager_base.html'%}
{% load static i18n l10n %}
{% block content%}
<style>
	.context{
		width: 10000px;
		height: 10000px;
		background-color: #ccc;
	}
</style>
<div class="context">
    <!-- <link rel="stylesheet" href="{% static 'css/matrix.css' %}"> -->
    <div class="container con-matrix">
            
    </div>
</div>    
{% endblock %}