api/urls.py
from rest_framework.routers import SimpleRouter
from .views import UserViewSet, HistoryList, ResourcesList, NewsList

router = SimpleRouter()

router.register('users', UserViewSet, 'users')
router.register('history', HistoryList, 'history')
router.register('resources', ResourcesList, 'resources')
router.register('news', NewsList, 'news')

urlpatterns = router.urls

bayel_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from balance.views import SearchHistoryView
from bayel_project import settings
from pages.views import ReportSearchView, SendFormTelegram
from users.views import SearchResultsView, OperatorDetails

handler404 = 'pages.views.my_404'
handler403 = 'pages.views.my_403'
handler400 = 'pages.views.my_400'
handler503 = 'pages.views.my_503'

urlpatterns = [
    path('bashkaru/nurlan', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('rest_auth.urls')),
]

urlpatterns += i18n_patterns(
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('balance/', include('balance.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('search_history/', SearchHistoryView.as_view(), name='search_history'),
    path('report_search/', ReportSearchView.as_view(), name='report_search'),
    path('send-form-tg/', SendFormTelegram.as_view(), name='send_message'),

    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

balance/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.utils.datetime_safe import datetime
from users.models import CustomUser, Office


class History(models.Model):
    history_username = models.CharField(verbose_name='Логин пользователя ', max_length=100)
    history_user_fullname = models.CharField(verbose_name='ФИО пользователя', max_length=100)
    history_user_id = models.IntegerField(verbose_name='id пользователя')
    history_blank = models.CharField(default='', max_length=1, verbose_name='Пустышка')
    history_amount = models.IntegerField(verbose_name='Сумма')
    history_remark = models.TextField(verbose_name=_(u'Билдирүү'))
    history_date = models.DateTimeField(verbose_name='Дата операции', auto_now_add=True)
    history_operator = models.CharField(verbose_name='Оператор', max_length=100, null=True, blank=True)
    history_office = models.CharField(verbose_name='Офис', max_length=150, null=True, blank=True)

    def __str__(self):
        return f'{self.history_username} - {self.history_amount} -------- {self.history_date}'


class History13(models.Model):
    history_username13 = models.CharField(verbose_name='Логин пользователя 13', max_length=100)
    history_user_fullname13 = models.CharField(verbose_name='ФИО пользователя 13', max_length=100)
    history_user_id13 = models.IntegerField(verbose_name='id пользователя 13')
    history_blank13 = models.CharField(default='', max_length=1, verbose_name='Пустышка 13')
    history_amount13 = models.IntegerField(verbose_name='Сумма 13')
    history_remark13 = models.TextField(verbose_name=_(u'Билдирүү 13'))
    history_date = models.DateTimeField(verbose_name='Дата операции 13', auto_now_add=True)
    history_operator13 = models.CharField(verbose_name='Оператор 13', max_length=100, null=True, blank=True)
    history_office13 = models.CharField(verbose_name='Офис 13', max_length=150, null=True, blank=True)

    def __str__(self):
        return f'{self.history_username13} - {self.history_amount13} -------- {self.history_date}'


@receiver(post_save, sender=History)
def followers_check(sender, instance, **kwargs):
    user_bal = CustomUser.objects.get(username=instance.history_username)
    user_bal.user_balance -= int(instance.history_amount)
    user_bal.save()


@receiver(post_delete, sender=History)
def check_history(sender, instance, **kwargs):
    try:
        user_bal = CustomUser.objects.get(username=instance.history_username)
        user_bal.user_balance += int(instance.history_amount)
        user_bal.save()
    except ObjectDoesNotExist as e:
        print('Object Does not exist')


@receiver(post_save, sender=History13)
def followers_check13(sender, instance, **kwargs):
    user_bal = CustomUser.objects.get(username=instance.history_username13)
    user_bal.user_balance13 -= int(instance.history_amount13)
    user_bal.save()


@receiver(post_delete, sender=History13)
def check_history13(sender, instance, **kwargs):
    try:
        user_bal = CustomUser.objects.get(username=instance.history_username13)
        user_bal.user_balance13 += int(instance.history_amount13)
        user_bal.save()
    except ObjectDoesNotExist as e:
        print('Object Does not exist')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Office
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label="Логин", error_messages={'required': _(u"Бул тилке бош")}, required=True,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Логин'}))
    user_fullname = forms.CharField(label=_(u'Аты Жөнү'), error_messages={'required': _(u"Бул тилке бош")},
                                    required=True,
                                    widget=forms.TextInput(
                                        attrs={'class': 'form-control', 'placeholder': _(u'Аты Жөнү')}))
    user_phone = forms.CharField(label="Телефон", error_messages={'required': _(u"Бул тилке бош")}, required=True,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': _(u'Телефон номери')}))
    user_by_whom = forms.ModelChoiceField(label=_(u'Жетекчи'), required=False,
                                          queryset=CustomUser.objects.filter(is_staff=False,
                                                                             follower2=None),
                                          empty_label=_(u"Кимден"),
                                          widget=forms.Select(attrs={'class': 'form-control ', 'data-plugin': 'select2',
                                                                     'data-minimum-input-length': '1'}))
    user_office = forms.ModelChoiceField(label=_(u'Регион'), required=True,
                                         queryset=Office.objects.all(),
                                         empty_label=_(u"Регион"),
                                         widget=forms.Select(attrs={'class': 'form-control my-form'}))
    password1 = forms.CharField(label=_(u'Сыр сөз'), error_messages={'required': _(u"Бул тилке бош")}, required=True,
                                min_length=8, validators=[
            RegexValidator('^(\w+\d+|\d+\w+)+$',
                           message=_(u'Сырсөз англис тамга жана сандардан жыйындысы болуп саналат'))],
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control',
                                           'placeholder': _(u'Сыр сөз'), 'value': 'bayel123'}), )
    password2 = forms.CharField(label=_(u'Сыр сөздү кайталаңыз'), error_messages={'required': _(u"Бул тилке бош")},
                                required=True,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': _(u'Сыр сөздү кайталаңыз'),
                                           'value': 'bayel123'}))
    terms = forms.BooleanField(label=_(u'Мен "Бай Эл" программасынын  Купуялык саясатын окуп чыгып, кабыл алып жатам'),
                               error_messages={'required': _(u"Бул тилке бош")}, required=True,
                               widget=forms.CheckboxInput(
                                   attrs={'class': 'form-control terms',
                                          'onclick': "showMe('autoUpdate', 'picture-signup')",
                                          'checked': 'true'}), )

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            'username', 'user_fullname', 'user_phone', 'user_by_whom', 'user_office',)

    def clean_username(self):
        username = self.cleaned_data['username']
        r = CustomUser.objects.filter(username=username)
        if r.count():
            raise ValidationError("Логин уже используется, пожалуйста введите другой логин")
        return username

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Пароли не совпадают")
        return password2


class CustomUserChangeForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        self.fields['user_by_whom'].queryset = CustomUser.objects.filter(is_staff=False)
        password = forms.CharField(label=False)

    username = forms.CharField(label="Логин", error_messages={'required': _(u"Бул тилке бош")}, required=True,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Логин'}))
    user_fullname = forms.CharField(label=_(u'Аты Жөнү'), error_messages={'required': _(u"Бул тилке бош")},
                                    required=True,
                                    widget=forms.TextInput(
                                        attrs={'class': 'form-control', 'placeholder': _(u'Аты Жөнү')}))
    user_notes = forms.CharField(label=_(u'Белги'), required=False,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': _(u'Белги')}))
    user_office = forms.ModelChoiceField(label=_(u'Регион'), required=True,
                                         queryset=Office.objects.all(),
                                         empty_label=_(u"Регион"),
                                         widget=forms.Select(attrs={'class': 'form-control my-form'}))
    user_by_whom = forms.ModelChoiceField(label=_(u'Жетекчи'), required=False,
                                          queryset=CustomUser.objects.filter(is_staff=False,
                                                                             follower2=None),
                                          empty_label=_(u"Кимден"),
                                          widget=forms.Select(attrs={'class': 'form-control ', 'data-plugin': 'select2',
                                                                     'data-minimum-input-length': '1'}))
    user_phone = forms.CharField(label="Телефон", error_messages={'required': _(u"Бул тилке бош")}, required=True,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': _(u'Телефон')}))
    user_balance = forms.CharField(label="Доступно для снятия", error_messages={'required': _(u"Бул тилке бош")},
                                   required=True,
                                   widget=forms.TextInput(
                                       attrs={'class': 'form-control', 'placeholder': _(u'Доступно для снятия')}))
    user_total_balance = forms.CharField(label="Всего заработанно", error_messages={'required': _(u"Бул тилке бош")},
                                         required=True,
                                         widget=forms.TextInput(
                                             attrs={'class': 'form-control', 'placeholder': _(u'Всего заработанно')}))
    user_balance13 = forms.CharField(label="Доступно для снятия 13", error_messages={'required': _(u"Бул тилке бош")},
                                     required=True,
                                     widget=forms.TextInput(
                                         attrs={'class': 'form-control', 'placeholder': _(u'Доступно для снятия 13')}))
    user_total_balance13 = forms.CharField(label="Всего заработанно 13",
                                           error_messages={'required': _(u"Бул тилке бош")},
                                           required=True,
                                           widget=forms.TextInput(
                                               attrs={'class': 'form-control',
                                                      'placeholder': _(u'Всего заработанно 13')}))
    user_balance13_hidden = forms.CharField(label="Скрыто 13",
                                            error_messages={'required': _(u"Бул тилке бош")},
                                            required=True,
                                            widget=forms.TextInput(
                                                attrs={'class': 'form-control',
                                                       'placeholder': _(u'Скрыто 13')}))
    followers = forms.CharField(label="Подписчики", error_messages={'required': _(u"Бул тилке бош")},
                                required=True,
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control', 'placeholder': _(u'Подписчики')}))
    followers13 = forms.CharField(label="Подписчики 13", error_messages={'required': _(u"Бул тилке бош")},
                                  required=True,
                                  widget=forms.TextInput(
                                      attrs={'class': 'form-control', 'placeholder': _(u'Подписчики 13')}))
    followers13_passive = forms.CharField(label="Подписчики скрытые 13",
                                          error_messages={'required': _(u"Бул тилке бош")},
                                          required=True,
                                          widget=forms.TextInput(
                                              attrs={'class': 'form-control',
                                                     'placeholder': _(u'Подписчики скрытые 13')}))

    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            'username', 'user_fullname', 'user_image', 'user_by_whom', 'user_phone', 'user_balance13',
            'user_total_balance13', 'status_user_own', 'product13', 'followers13',

templates/history/histories13_list.html
{% extends 'manager_base.html' %}
{% load i18n l10n %}
{% block content %}
    <!-- Page -->
    <div class="page">
        <div class="page-header">
            <h1 class="page-title"></h1>
        </div>
        <div class="page-content container-fluid">

            <div class="row">
                <div class="col-xl-12">
                    <!-- Panel Filtering rows -->
                    <div class="panel balance-history">
                        <header class="panel-heading">
                            <h3 class="panel-title">{% trans "Каржынын тарыхы" %} {{ user_in.user_fullname }}</h3>
                            {% if user.is_superuser %}
                                <a href="{% url 'export_balance13' user_his=user_in.id %}"
                                   class="btn btn-outline-primary"
                                   style="margin: 0 0 10px 30px; font-weight: 500; text-transform: uppercase">
                                    Скачать список
                                </a>
                            {% endif %}
                        </header>

                        <div class="panel-body">
                            <table class="table table-bordered table-hover toggle-circle" id="exampleFootableFiltering"
                                   data-paging="true" data-filtering="true" data-sorting="true">
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th data-name="something" data-visible="true"
                                        data-filterable="false">{% trans "Алган күнү" %}</th>
                                    <th data-name="firstName">{% trans "Сумма" %}</th>
                                    <th data-name="firstName">{% trans "билдирүү" %}</th>
                                    {% if user.is_superuser %}
                                        <th></th>
                                    {% endif %}
                                </tr>
                                </thead>
                                <tbody>
                                {% for info in object_list %}
                                    <tr>
                                        <td class="counterCell"></td>
                                        <td>{{ info.history_date }}</td>
                                        <td>{{ info.history_amount13 }}</td>
                                        <td>{{ info.history_remark13 }}</td>
                                        {% if user.is_superuser %}
                                            <td>
                                                <a href="{% url 'history13_delete' info.pk %}?next={{ request.path|urlencode }}"
                                                   style="background:red; color:#fff; font-weight:700; font-size:13px; padding:4px 10px; border-radius: 6px;"><i
                                                        class="icon wb-trash"></i></a>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- End Panel Filtering -->
                </div>

            </div>
        </div>
    </div>
    <!-- End Page -->

{% endblock %}

templates/history/history13_create.html
{% extends 'manager_base.html' %}
{% load static i18n crispy_forms_tags %}
{% block content %}

    <!-- Features start -->
    <section id="page">

    <div class="page-header">
        </div>
        <div class="container mb-70">
            <div class="row">
                <div class="col-md-12">
                    <div class="main-title wow fadeIn" data-wow-delay="300ms">
                        <h2 class="white">Выдать "{{ user_info.username }}" - {{ user_info.user_fullname }}?</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h4 class="white">Доступно для снятия: {{ user_info.user_balance13 }} б.</h4>
                    <form class="white" action="" method="post" novalidate="novalidate">
                        {% csrf_token %}
                        {{ form.history_amount13|as_crispy_field }}
                        {{ form.history_remark13|as_crispy_field }}
                        <div class="btn-signup">
                            <button type="submit" class="btn btn-success signup-btn">{% trans 'Сактоо' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Features ends -->

{% endblock %}

templates/history/history13_delete.html
{% extends 'manager_base.html' %}
{% block content %}
    <!-- Features start -->
    <section id="features">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="main-title wow fadeIn" data-wow-delay="300ms">
                        <h2>Вы действительно хотите удалить запись {{ object.history_amount13 }}? </h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <form action="" method="post" novalidate="novalidate">
                        {% csrf_token %}
                        <div class="btn-signup">
                            <button type="submit" class="btn btn-outline-danger signup-btn">Удалить</button>
                            <a href="{% url 'users_list' %}" class="btn btn-outline-success signup-btn">Нет</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Features ends -->
{% endblock %}

templates/history/history_create.html
{% extends 'manager_base.html' %}
{% load static i18n %}
{% block content %}

    <!-- Features start -->
    <section class="page">
        <div class="page-header">
        </div>
        <div class="container mb-70">
            <div class="row">
                <div class="col-md-12">
                    <div class="main-title wow fadeIn" data-wow-delay="300ms">
                        <h2 class="white">Выдать "{{ user_info.username }}" - {{ user_info.user_fullname }}?</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <style>
                    label[for="id_history_amount"], label[for="id_history_remark"] {
                        color: #fff
                    }
                </style>
                <div class="col-md-6">
                    <h4 class="white">Заработанно в общем: {{ new_balance.user_total }} б.</h4>
                    {% if not user_info.user_second_status %}
                        <h4 class="white">Заблокированные для перехода на третий уровень: {{ new_balance.user_frozen }}
                            б.</h4>
                    {% endif %}
                    <h4 class="white">Доступно для снятия: {{ new_balance.user_balance }} б.</h4>
                    <form action="" method="post" novalidate="novalidate">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="btn-signup">
                            <button type="submit"
                                    class="btn btn-success signup-btn">{% trans 'Сактоо' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Features ends -->

{% endblock %}

templates/history/history_today.html
{% extends 'manager_base.html' %}
{% load i18n l10n %}
{% block content %}
    <!-- Page -->
    <div class="page">
        <div class="page-header">
            <h1 class="page-title"></h1>
        </div>
        <div class="page-content container-fluid">

            <div class="row">
                <div class="col-xl-12">
                    <!-- Panel Filtering rows -->
                    <div class="panel balance-history">
                        <header class="panel-heading" style="display: flex; justify-content: space-between">
                            <div class="title-first" style="display: flex">
                                <h2 class="panel-title">Сегодня получили</h2>
                                <span class="panel-title title-counters"><a
                                        class="history-print"
                                        href="
                                            {% if user_office_context and user_info %}
                                            {% url 'today_money_office_user' pk=user_office_context.office_name search=search_input %}
                                            {% elif user_office_context %}
                                            {% url 'today_money_office' pk=user_office_context.office_name %}
                                            {% elif user_info %}
                                            {% url 'user_bal_export' pk=search_input %}
                                            {% else %}
                                            {% url 'today_money' %}
                                            {% endif %}">Распечатать историю</a>
                                </span>
                            </div>

                            <div class="title-second">
                                <span class="panel-title-second">
                                    <form action="{% url 'search_history' %}"
                                          method="get">
                                        <input name="query" type="text" placeholder="Поиск"
                                               class="form-control inline-block width-30"
                                               width="300px !important" value="{{ search_input }}">

                                        <select name="user_office" class="form-control my-form inline-block width-30"
                                                id="id_user_office">
                                        {% if user_office_context %}
                                            <option value="{{ user_office_context.office_name }}"
                                                    selected="">{{ user_office_context.office_name }}</option>
                                        {% else %}
                                            <option value="" selected="">Регион</option>
                                        {% endif %}
                                            <option value="">Все</option>
                                            {% for office in all_offices %}
                                                <option value="{{ office.office_name }}">{{ office.office_name }}</option>
                                            {% endfor %}
                                    </select>
                                    <button type="submit" class="btn btn-primary inline-block"
                                            style="margin-left: 10px; width: 16%;">Поиск
                                    </button>
                                    </form>
                                </span>
                            </div>
                        </header>

                        <div class="panel-body">
                            <table class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th data-name="firstName">Логин</th>
                                    <th data-name="something">Дата получения</th>
                                    <th data-name="something">Офис пользователя</th>
                                    <th class="text-center" data-name="firstName">Сумма</th>
                                    <th class="text-center" data-name="firstName">Кошелек</th>
                                    <th data-name="firstName">Ремарка</th>
                                    <th data-name="something">Оператор</th>
                                    {% if user.is_superuser %}
                                        <th></th>
                                    {% endif %}
                                </tr>
                                </thead>
                                <tbody>
                                {% for info in object_list %}
                                    <tr>
                                        <td class="counterCell"></td>
                                        <td>{% if info.history_username %}
                                            <a href="{% url 'user_detail' info.history_user_id %}"
                                               style="text-decoration: none">
                                                {{ info.history_username }}</a>
                                        {% else %}
                                            <a href="{% url 'user_detail' info.history_user_id13 %}"
                                               style="text-decoration: none">
                                                {{ info.history_username13 }}</a>
                                        {% endif %}
                                        </td>
                                        <td>{{ info.history_date|date:'d-m-Y H:i' }}</td>
                                        <td>{% if info.history_office %}{{ info.history_office }}{% else %}
                                            {{ info.history_office13 }}{% endif %}</td>
                                        <td class="text-center">{% if info.history_amount %}{{ info.history_amount }}{% else %}
                                            {{ info.history_amount13 }}{% endif %}</td>
                                        <td class="text-center">{% if info.history_amount %}
                                            <span class="badge-lg badge-success" style="padding: 5px;
                                                border-radius: 5px; font-size:14px">7600</span>
                                        {% elif info.history_amount13 %}
                                            <span class="badge-lg badge-info" style="padding: 5px;
                                                border-radius: 5px; font-size:14px">13000</span>
                                        {% endif %}</td>
                                        <td>{% if info.history_remark %}{{ info.history_remark }}{% else %}
                                            {{ info.history_remark13 }}{% endif %}</td>
                                        <td>{% if info.history_operator %}{{ info.history_operator }}{% else %}
                                            {{ info.history_operator13 }}{% endif %}</td>
                                        {% if user.is_superuser %}
                                            <td>
                                                <a href="{% url 'history_delete' info.pk %}?next={{ request.path|urlencode }}"
                                                   style="background:red; color:#fff; font-weight:700; font-size:13px; padding:4px 10px; border-radius: 6px;"><i
                                                        class="icon wb-trash"></i></a>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% include 'paginator.html' with page=page_obj %}
                        </div>
                    </div>
                    <!-- End Panel Filtering -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Page -->

{% endblock %}