api/urls.py
from rest_framework.routers import SimpleRouter
from .views import UserViewSet, HistoryList, ResourcesList, NewsList

router = SimpleRouter()

router.register('users', UserViewSet, 'users')
router.register('history', HistoryList, 'history')
router.register('resources', ResourcesList, 'resources')
router.register('news', NewsList, 'news')

urlpatterns = router.urls

bayel_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from balance.views import SearchHistoryView
from bayel_project import settings
from pages.views import ReportSearchView, SendFormTelegram
from users.views import SearchResultsView, OperatorDetails

handler404 = 'pages.views.my_404'
handler403 = 'pages.views.my_403'
handler400 = 'pages.views.my_400'
handler503 = 'pages.views.my_503'

urlpatterns = [
    path('bashkaru/nurlan', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('rest_auth.urls')),
]

urlpatterns += i18n_patterns(
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('balance/', include('balance.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('search_history/', SearchHistoryView.as_view(), name='search_history'),
    path('report_search/', ReportSearchView.as_view(), name='report_search'),
    path('send-form-tg/', SendFormTelegram.as_view(), name='send_message'),

    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('list75/', UserList75.as_view(), name='users_list75'),
    path('list/', UserList.as_view(), name='users_list'),
    path('users_second_tour/', UsersSecondTour.as_view(), name='users_second_tour'),
    path('user_second_update/<int:pk>/<int:oper>/', UserSecondUpdate.as_view(), name='user_second_update'),
    path('users_reg/', UserRegTodayList.as_view(), name='users_today'),
    path('detail/<int:pk>/', UserDetail.as_view(), name='user_detail'),
    path('balance/<int:pk>/', UserBalance.as_view(), name='user_balance'),
    path('update/<int:pk>/<int:oper>/', UserUpdate.as_view(), name='user_update'),
    path('belgi_update/<int:pk>/<int:oper>/', BelgiUpdates.as_view(), name='belgi_update'),
    path('delete/<int:pk>/', UserDelete.as_view(), name='user_delete'),
    path('matrix_list/<int:pk>/', UserListMatrix.as_view(), name='matrix_list'),
    path('matrix/<int:pk>/', UserMatrixView.as_view(), name='user_matrix'),
    path('matrix13_list/<int:pk>/', UserListMatrix13.as_view(), name="matrix13_list"),
    path('matrix13/<int:pk>/', UserMatrix13View.as_view(), name='user_matrix13'),
    path('upload/<int:pk>/', PassportUploadView.as_view(), name='upload'),
    path('referral/<int:pk>/', ReferralCreateView.as_view(), name='referral_create'),
    path('changepswd/<int:pk>/', change_password, name='change_pswd'),
    path('signup/confirm/', SignUpConfirmPage.as_view(), name='confirm'),
    path('users_wait/', UserWaitList.as_view(), name='users_wait'),
    # Office urls
    path('offices_list/', OfficeList.as_view(), name='offices_list'),
    path('office_delete/<int:pk>/', OfficeDelete.as_view(), name='office_delete'),
    path('office_update/<int:pk>/', OfficeUpdate.as_view(), name='office_update'),
    path('office_create/', OfficeCreate.as_view(), name='office_create'),
    # Operator urls
    path('operator_list/', OperatorList.as_view(), name='operator_list'),
    path('operator_signup/', OperatorSignUp.as_view(), name='operator_signup'),
    path('operator_details/<int:pk>/', OperatorDetails.as_view(), name='operator_details'),
    # Login Page view
    path('login/', LoginPageView.as_view(), name='login'),
    path('user_message_block/<int:pk>/', user_message_block, name='user_message_block'),
    # Export xlwt all users
    path('export_xlwt/', export_xlwt, name='export_xlwt'),
]

users/models.py
from PIL import Image, ImageFile
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils.datetime_safe import datetime
from django.utils.translation import ugettext_lazy as _
from django.db import models

from image_compress.image_compress import compress_image

ImageFile.LOAD_TRUNCATED_IMAGES = True


class MyValidator(UnicodeUsernameValidator):
    regex = r'^[\w.@+\-]+$'
    message = _('Логин тамга жана сандардан гана турууга тийиш.')


# User office region
class Office(models.Model):
    office_name = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.office_name}'


# Create your models here.
class CustomUser(AbstractUser):
    username_validator = MyValidator()
    slug = models.SlugField(default='', editable=False, max_length=200, null=False)
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    user_fullname = models.CharField(max_length=255, verbose_name='Аты Жөнү')
    user_image = models.ImageField(verbose_name=_("Колдонуучунун суроту"), upload_to='users/',
                                   default='../static/default_user.png', null=True, blank=True)
    user_passport = models.ImageField(upload_to='users/', default='../static/default.png', null=True, blank=True,
                                      verbose_name='Фотография паспорта')
    user_phone = models.CharField(verbose_name=_("Телефон номери"), max_length=60, null=True,
                                  blank=True)

    # User sponsor
    user_by_whom = models.ForeignKey('self', related_name='users_by', verbose_name=_("Кимден"),
                                     on_delete=models.SET_NULL, null=True,
                                     blank=True)

    # User balance information
    user_balance = models.IntegerField(default=0, verbose_name=_("Алууга мүмкүнчүлүк"))
    user_total_balance = models.IntegerField(default=0, verbose_name='Мен таптым')

    user_balance13_hidden = models.IntegerField(default=0, verbose_name=_("Жашыруун баланс 13"))
    user_balance13 = models.IntegerField(default=0, verbose_name=_("Алууга мүмкүнчүлүк 13"))
    user_total_balance13 = models.IntegerField(default=0, verbose_name=_('Мен таптым 13'))

    # User registration date
    user_registration_date = models.DateTimeField(verbose_name='Дата регистрации', default=datetime.now)

    # User office region
    user_office = models.ForeignKey(Office, on_delete=models.SET_NULL, related_name='user_region', null=True,
                                    blank=True, verbose_name='Офис пользователя')

    # Followers quantity
    followers = models.IntegerField(verbose_name=_('Жолдоочулары'), default=0)
    followers13 = models.IntegerField(verbose_name=_('Жолдоочулары 13'), default=0)
    followers13_passive = models.IntegerField(verbose_name=_('Жашыруун Жолдоочулары 13 '), default=0)

    # First follower
    follower1 = models.ForeignKey('CustomUser', on_delete=models.SET_NULL, related_name='followers_1', null=True,
                                  blank=True, verbose_name='Первый подписчик')
    follower1_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации 1 подписчика')
    follower1_13_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации 1 13 подписчика')

    # Second follower
    follower2 = models.ForeignKey('CustomUser', on_delete=models.SET_NULL, related_name='followers_2', null=True,
                                  blank=True, verbose_name='Второй подписчик')
    follower2_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации 2 подписчика')
    follower2_13_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации 2 13 подписчика')

    # User registration status
    status = models.BooleanField(verbose_name=_('Статус'), default=False)
    status_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи статуса')
    status13 = models.BooleanField(verbose_name=_('Статус 13'), default=False)
    status_date13 = models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи статуса 13')

    # Product and the date when product was given to the user.
    product = models.BooleanField(default=False, verbose_name=_('Продукция'))
    product_given_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи продукции')
    product13 = models.BooleanField(default=False, verbose_name=_('Продукция 13'))
    product_given_date13 = models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи продукции 13')

    # terms and conditions
    terms = models.BooleanField(default=False, verbose_name='Политика конфиденциальности')

    # User information to the staff
    user_notes = models.CharField(max_length=155, verbose_name='Заметки', blank=True, null=True)
    user_notes_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата заметки')
    user_notes_user = models.ForeignKey('CustomUser', on_delete=models.SET_NULL, related_name='user_notes_changed',
                                        null=True, blank=True, verbose_name='Оператор заметки')

    # For cashiers
    is_cashier = models.BooleanField(verbose_name='Кассир', default=False)

    # Place in list by updated information
    updating_operator = models.ForeignKey('CustomUser', on_delete=models.SET_NULL, related_name='updated_operator',
                                          blank=True, null=True, verbose_name='Последний оператор')
    # Last time and data when was the model updated
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    # Gift place for users
    status_user_gift = models.BooleanField(default=False, verbose_name='Без денег')
    status_user_gift13 = models.BooleanField(default=False, verbose_name='Первый без денег 13')
    status_user_own = models.BooleanField(default=False, verbose_name='Первый без денег 75')

    # User greetings message
    user_message = models.BooleanField(default=True, verbose_name='Статус приветственного сообщение ')

    # User status for moving to third tour
    user_second_tour = models.BooleanField(default=False, verbose_name='Статус готовности перехода на 3 уровень')

    # User has a status for third tour
    user_second_status = models.BooleanField(default=False, verbose_name='Статус получения 3 уровня')

    def __str__(self):
        return f'{self.username}'


class UserFollowers(models.Model):
    top_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='top_user_info')
    follower_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='follower_user_info')
    follower_date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f'{self.top_user}'


class OperationHistory(models.Model):
    oper_his_operator = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)
    oper_his_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='oper_his_user_info')
    oper_his_action = models.CharField(max_length=50)
    oper_his_note = models.CharField(max_length=255)
    oper_his_date = models.DateTimeField(default=datetime.now)
    oper_his_amount = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.oper_his_operator} ---- {self.oper_his_action} ---- {self.oper_his_user}'


@receiver(post_save, sender=CustomUser)
def registration(sender, instance, created, **kwargs):
    if instance.status and instance.status_date is None and not instance.is_cashier and not instance.is_staff:
        def date_legs(user_instance):
            # Save date and time, when user got the approval for status
            main_user = CustomUser.objects.get(id=user_instance.id)
            main_user.status_date = datetime.now()
            main_user.save()

            # Saving instance user to one of the legs of his sponsor
            if user_instance.user_by_whom:
                first_sponsor = CustomUser.objects.get(id=user_instance.user_by_whom.id)
                if not first_sponsor.follower1:
                    first_sponsor.follower1 = user_instance
                    first_sponsor.follower1_date = datetime.now()
                elif not first_sponsor.follower2:
                    first_sponsor.follower2 = user_instance
                    first_sponsor.follower2_date = datetime.now()
                first_sponsor.save()

        def money_transfer(first_leg, count, amount, first_user):
            sponsor = CustomUser.objects.get(id=first_leg.user_by_whom.id)
            sponsor.user_balance += amount
            sponsor.user_total_balance += amount
            sponsor.followers += 1
            UserFollowers.objects.create(top_user=sponsor, follower_user=first_user, follower_date=datetime.now())
            if amount != 0:
                OperationHistory.objects.create(oper_his_operator=first_user,
                                                oper_his_user=sponsor, oper_his_amount=amount,
                                                oper_his_note=f'Получил(а) наличные за подписчика {first_user.user_fullname}',
                                                oper_his_action='money')
            sponsor.save()
            count += 1
            if count <= 10 and first_user.status_user_gift and sponsor.user_by_whom:
                money_transfer(sponsor, count, 0, first_user)
            elif count <= 10 and not instance.status_user_gift:

templates/users/matrix.html
{% extends 'manager_base.html' %}
{% load static i18n l10n %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/table-matrix.css' %}">

<div class="main">
    <div class="table-block">
        <table class="table table-bordered toggle-circle table-list-matrix"> 
        <thead> 
            <tr>
                <th class='text-center title' colspan='3'>Структура</th>
            </tr>
            <tr>
                <th class='text-center' width='10%'>Позиция</th>
                <th>ФИО</th>
                <th>Кимден</th>
            </tr>
            </thead>              
            {% for item in data %}
                {% if item.key != 0.0 %}
                    <tr>
                        {% if item.tens != 'null' %}
                        <th class='text-center'>{{item.tens}}</th>
                        {% else %}
                        <th class='text-center'>{{item.key}}</th>
                        {% endif %}
                        <th>{{item.title}} - ({{item.name}})</th>
                        <th>{{item.parent}}</th>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
    </div>
</div>
    
{% endblock %}

templates/users/matrix13.html
{% extends 'manager_base.html' %}
{% load static i18n l10n %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/table-matrix.css' %}">

<div class="main">
    <div class="table-block">
        <table class="table table-bordered toggle-circle table-list-matrix"> 
        <thead> 
            <tr>
                <th class='text-center title' colspan='4'>Структура</th>
            </tr>
            <tr>
                <th class='text-center' width='10%'>Позиция</th>
                <th>ФИО</th>
                <th>Статус 3 уровня</th>
                <th>Кимден</th>
            </tr>
            </thead>              
            {% for item in data %}
                {% if item.key != 0.0 %}
                    <tr>
                        {% if item.tens != 'null' %}
                        <th class='text-center'>{{item.tens}}</th>
                        {% else %}
                        <th class='text-center'>{{item.key}}</th>
                        {% endif %}
                        <th>{{item.title}} - ({{item.name}})</th>
                        <th>{{item.status13}}</th>
                        <th>{{item.parent}}</th>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
    </div>
</div>
    
{% endblock %}

templates/users/passport_upload.html
{% extends 'manager_base.html' %}
{% load static i18n %}
{% block content %}
    <div class="container mt-40">
        <h3>{% trans 'Колдонуучу дайындарын өзгөртүү' %}</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="id_user_passport">{% trans 'Паспорттун сүрөтү' %}:
            </label> {% trans 'Азыркы учурда' %}:
            <a href="{{ object.user_passport.url }}">{{ object.user_passport }}</a>
            {% trans 'өзгөртүү' %}:
            <input type="file" name="user_passport" class="form-control" accept="image/*"
                   id="id_user_passport">

            <label for="id_user_image" class="mt-15">{% trans 'Колдонуучунун сүрөтү' %}:
            </label> {% trans 'Азыркы учурда' %}:
            <a href="{{ object.user_image.url }}">{{ object.user_image }}</a>
            {% trans 'өзгөртүү' %}:
            <input type="file" name="user_image" accept="image/*" id="id_user_image" class="form-control">

            <label for="id_user_fullname" class="mt-15">{% trans 'Аты Жөнү' %}:</label>
            <input type="text" value="{{ object.user_fullname }}" name="user_fullname" id="id_user_fullname"
                   class="form-control">

            <label for="id_user_phone" class="mt-15">{% trans 'Телефон номери' %}:</label>
            <input type="text" value="{{ object.user_phone }}" name="user_phone" id="id_user_phone"
                   class="form-control">

            <button type="submit" class="btn btn-success mt-10">{% trans 'Өзгөртүү' %}</button>
        </form>
    </div>

{% endblock %}

templates/users/user_message_block.html
{% extends 'manager_base.html' %}
{% load static %}
{% block content %}
    <!-- Page -->
    <div class="page">
        <div class="page-header">
            <h1 class="page-title">asdf</h1>
        </div>
        <div class="main-message">
            <h1 style="">Приветствие было успешно отправлено участнику: </h1>
            <h3> Логин:   {{ object.username }}</h3>
            <h3> ФИО:   {{ object.user_fullname }}</h3>
            <div class="row but-message-back">
            <a href="{% url 'user_detail' object.pk %}" class="btn btn-info">Назад в профиль</a></div>
        </div>
    </div>
{% endblock content %}

templates/users/user_second_update.html
{% extends 'manager_base.html' %}
{% load i18n %}
{% block content %}
    <!-- Features start -->
    <section >
    <div class="page-header">
            <h1 class="page-title">{% trans "Колдонуучулардын тизмеси" %}</h1>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="main-title wow fadeIn" data-wow-delay="300ms">
                        <h2 style="color: #fff">Вы действительно хотите перевести на третий уровень пользователя {{ object.username }}</h2>
                    </div>
                </div>
            </div>
            <div class="row mb-70">
                <div class="col-md-6">
                    <form action="" class="user-update-form" enctype="multipart/form-data" method="post"
                          novalidate="novalidate" id="myForm">
                        {% csrf_token %}


                        <p><label style="color: #fff; margin: 3rem 0" for="id_user_second_status">Перевести на третий уровень:</label>
                            {{ form.user_second_status }}</p>


                        <div class="btn-signup">
                            <button type="submit" class="btn btn-success signup-btn">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Features ends -->


{% endblock %}

templates/users/user_update.html
{% extends 'manager_base.html' %}
{% load i18n %}
{% block content %}
    <!-- Features start -->
    <section id="features" style="padding: 1rem 0;">
        <div class="container">
            <div class="row mb-70">
                <div class="col-md-12">
                    <form action="" class="user-update-form" enctype="multipart/form-data" method="post"
                          novalidate="novalidate" id="myForm">
                        {% csrf_token %}
                        <div class='col-md-12' style="display: inline-flex;">
                            <div class='col-md-6'>
                                <p><label for="id_username">Логин:</label>{{ form.username }}</p>
                                <p><label for="id_user_fullname">ФИО:</label>{{ form.user_fullname }}</p>
                                <p><label for="id_user_notes">Белги:</label>{{ form.user_notes }}</p>
                                <p><label for="id_user_image">Фотография пользователя:</label>{{ form.user_image }}</p>
                                <p><label for="id_user_office">Регион:</label>{{ form.user_office }}</p>
                                <p><label for="id_user_by_whom">Спонсор:</label>{{ form.user_by_whom }}</p>

                                {% if object.user_by_whom %}
                                    <p>{% if object.user_by_whom.follower1 %}
                                        1 Жолдоочу 7500:
                                        <a href="{% url 'user_detail' object.user_by_whom.follower1.pk %}">{{ object.user_by_whom.follower1 }}</a>
                                    {% else %}
                                        <span class="jok-red">1 Жолдоочу 7500: Жок</span>
                                    {% endif %}</p>
                                    <p>{% if object.user_by_whom.follower2 %}
                                        2 Жолдоочу 7500:
                                        <a href="{% url 'user_detail' object.user_by_whom.follower2.pk %}">{{ object.user_by_whom.follower2 }}</a>
                                    {% else %}
                                        <span class="jok-red">2 Жолдоочу 7500: Жок</span>
                                    {% endif %}</p>
                                {% endif %}

                                <p><label for="id_user_second_status">Переход на третий
                                    этап:</label>{{ form.user_second_status }}</p>
                            </div>
                            <div class='col-md-6'>

                                <p><label for="id_user_phone">Телефон:</label> {{ form.user_phone }}</p>

                                <table class="table table-bordered text-center">
                                    <tbody>
                                    <tr>
                                        <td class="vertical-middle">Доступно для снятия:</td>
                                        <td class="vertical-middle">{{ form.user_balance }}</td>
                                        <td class="vertical-middle">Всего заработанно:</td>
                                        <td class="vertical-middle">{{ form.user_total_balance }}</td>
                                    </tr>
                                    <tr>
                                        <td class="vertical-middle">Доступно для снятия 13:</td>
                                        <td class="vertical-middle">{{ form.user_balance13 }}</td>
                                        <td class="vertical-middle">Всего заработанно 13:</td>
                                        <td class="vertical-middle">{{ form.user_total_balance13 }}</td>
                                    </tr>
                                    <tr>
                                        <td class="vertical-middle">Скрытые деньги 13:</td>
                                        <td class="vertical-middle">{{ form.user_balance13_hidden }}</td>
                                        <td class="vertical-middle">Подписчики скрытые 13:</td>
                                        <td class="vertical-middle">{{ form.followers13_passive }}</td>
                                    </tr>
                                    <tr>
                                        <td class="vertical-middle">Подписчики:</td>
                                        <td class="vertical-middle">{{ form.followers }}</td>
                                        <td class="vertical-middle">Подписчики 13:</td>
                                        <td class="vertical-middle">{{ form.followers13 }}</td>
                                    </tr>
                                    </tbody>
                                </table>

                                <table class="table table-bordered text-center">
                                    <tbody>


                                    <tr>
                                        <td class="vertical-middle">Продукция:</td>
                                        <td class="vertical-middle">{{ form.product }}</td>
                                        <td class="vertical-middle">Продукция 13:</td>
                                        <td class="vertical-middle">{{ form.product13 }}</td>
                                        <td class="vertical-middle">Приветствие:</td>
                                        <td class="vertical-middle">{{ form.user_message }}</td>
                                    </tr>
                                    <tr>
                                        <td class="vertical-middle">Оператор:</td>
                                        <td class="vertical-middle">{{ form.is_staff }}</td>
                                        <td class="vertical-middle">Кассир:</td>
                                        <td class="vertical-middle">{{ form.is_cashier }}</td>
                                    </tr>
                                    <tr>
                                        <td class="vertical-middle">Статус &nbsp 7600:</td>
                                        <td class="vertical-middle">{% if object.user_by_whom %}
                                            <input
                                                    {% if not object.user_by_whom.status or object.user_by_whom.follower2 %}
                                                        style="visibility: hidden"
                                                    {% endif %}
                                                        type="checkbox" name="status" id="id_status"
                                                    {% if object.status %}
                                                        checked=""{% endif %}>
                                            {% if not object.user_by_whom.status %}
                                                <span class="jok-red">Спонсор {{ object.user_by_whom.user_fullname }}, Без Статуса</span>
                                            {% elif object.user_by_whom.follower2 %}
                                                <span class="jok-red">Спонсор занят</span>
                                            {% endif %}
                                        {% else %}
                                            <input style="visibility: hidden" type="checkbox" name="status"
                                                   id="id_status">
                                            <span class="jok-red">Спонсора нет</span>
                                        {% endif %}</td>
                                        <td class="vertical-middle">Первый без денег 75:</td>
                                        <td class="vertical-middle">{{ form.status_user_own }}</td>
                                        <td class="vertical-middle">Без денег:</td>
                                        <td class="vertical-middle">{{ form.status_user_gift }}</td>
                                    </tr>
                                    <tr>
                                        <td class="vertical-middle">Статус 13000:</td>
                                        <td class="vertical-middle"><input type="checkbox" name="status13"
                                                                           id="id_status13"
                                                                           {% if object.status13 %}checked=""{% endif %}>
                                        </td>
                                        <td class="vertical-middle">Первый без денег 13:</td>
                                        <td class="vertical-middle">{{ form.status_user_gift13 }}</td>
                                    </tr>
                                    </tbody>
                                </table>

                                <div class="btn-signup">
                                    <button type="submit" class="btn btn-outline-success signup-btn">Сохранить</button>

                                    <a href='https://web.whatsapp.com/send?phone={{ object.user_phone|slice:"1:" }}&text=Кутман күн Урматтуу {{ object.user_fullname }}! Сиз "Бай Эл.kg" программасына ийгиликтүү катталышыңыз менен куттуктайбыз! %0aСиздин логиниз: {{ object.username }} Сыр сөз (пароль): bayel123 колдонуп http://bayel.kg/users/login/ сайтына кириңиз. %0aДайыма кабардар болуш үчүн шилтемени колдонуп https://t.me/joinchat/PFuMAxnmBCAjmsxeT7AEXA Телеграм группага кошулуңуз. Ишиңизге ийгилик! %0aПрограмманын администрациясы.'
                                       target="_blank"
                                       class="btn btn-outline-success"
                                    >Саламдашуу</a>
                                    <a href='https://web.whatsapp.com/send?phone={{ object.user_phone|slice:"1:" }}&text=Добрый день Уважаемый {{ object.user_fullname }}! Поздравляем с успешной регистрацией в программе "Бай Эл.kg"! %0aПерейдите по адресу http://bayel.kg/users/login/ используя Ваш логин: {{ object.username }} пароль: bayel123 %0aПрисоединяйтесь к группе Telegram по ссылке https://t.me/joinchat/PFuMAxnmBCAjmsxeT7AEXA, чтобы быть в курсе событий. Удачи в работе! %0aАдминистрация программы.'
                                       target="_blank"
                                       class="btn btn-outline-success"
                                    >Приветствие</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Features ends -->

    <script>
        let u_s_s = document.getElementById('id_user_second_status');
        u_s_s.setAttribute('enabled', '');
    </script>

{% endblock %}